package day18;

public enum USAEnum {
    NEW_YEARS_DAY,
    BIRTHDAY_OF_MARTIN_LUTHER_KING_JR,
    MEMORIAL_DAY,
    INDEPENDENCE_DAY,
    LABOR_DAY,
    COLUMBUS_DAY,
    VETERANS_DAY,
    THANKSGIVING_DAY,
    CHRISTMAS_DAY
}
